[server]
host = "0.0.0.0"
port = 8080

[app]
log_level = "debug"

[mysql]
host      = "localhost"
port      = "3306"
user      = "root"
password  = "password"
db_name   = "garbage_category_rule_quiz"
ssl_mode  = "disable"
