services:
  db:
    image: mysql:8
    container_name: db-move-rule
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-move-rule}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
